### ISSUE TITLE
add plist examples and documentation to readme

### ISSUE THREAD

**Issue by jonschlinkert** [doowb/grunt-convert#16]

**Comment by hariadi** [comment]
Can we add [assemble-internal](https://github.com/assemble/assemble-internal) for auto generate readme :dancer:

**Comment by jonschlinkert** [comment]
I might have something better in a little bit :-)

**Comment by hariadi** [comment]
:+1:  :shipit:

**Comment by jonschlinkert** [comment]
@hariadi / @doowb see: https://github.com/assemble/grunt-readme

It's not finished, but I ran out of time today so I figured I'd push it up to get feedback. Let me know how we can improve it.

**Comment by hariadi** [comment]
Done with 2b444cf.
