### ISSUE TITLE
xml2json not writing the output file

### ISSUE THREAD

**Issue by jdiprizio** [doowb/grunt-convert#25]
Since 0.1.7 changes, xml2json conversion does not write the output file.

Issue is at line 94, after :

``` javascript
data = JSON.stringify(result, null, options.indent);
```

It immediately finishes and goes to the next file though it's marked as handled = true.

Right after line 94 you should add:

``` javascript
grunt.file.write(f.dest, data);
```

**Comment by doowb** [comment]
Thanks for pointing this out. I had done a quick fix for the async stuff, but should have really tried to refactor this more so I wouldn't miss parts like that.

**Comment by doowb** [comment]
Closed with https://github.com/assemble/grunt-convert/commit/35404d7225f700e60b02fcab9c98aa734e38784a
