### ISSUE TITLE
Not converting multiple files

### ISSUE THREAD

**Issue by aholla** [doowb/grunt-convert#29]
Hi, I am trying to convert XML to JSON. I have 3 files, all three are duplicated and renamed "json" but only the first is actually converted to json, the rest remain xml files.

This only happens if I specify a type:
options: {
    type: 'xml'
}

I have multiple file types that are xml but with different extensions: "pex", "fnt" etc...

Thanks

**Comment by hariadi** [comment]
Related #24

**Comment by aholla** [comment]
Hi, what am I meant to do to fix this? It does not work and I have version 1.0.9.

**Comment by doowb** [comment]
Fixed by https://github.com/assemble/grunt-convert/commit/ead845ae23786743b8ab53a4c726b08fcaa18916

There was a logic issue with the `options.type`. I added more tests around it too.

**Comment by aholla** [comment]
Brilliant! All working at my end. Thank you thank you thank you!
