### ISSUE TITLE
yml2json parsing multi-line strings adds unwanted line break.

### ISSUE THREAD

**Issue by richburdon** [doowb/grunt-convert#46]
Multiline strings append "\n" to the generated string.

foo: >
  a
  b
  c

generates:

  "foo": "a b c\n"

http://symfony.com/doc/current/components/yaml/yaml_format.html

**Comment by doowb** [comment]
`grunt-convert` uses [yamljs](https://github.com/jeremyfa/yaml.js) for parsing yaml to json. Using yamljs directly results in the same output as you have above. You can open an issue there if you feel that it's a bug.

I'm also working on a refactor of [converter](https://github.com/doowb/converter) that will be used here when it's finished. This will let you use custom converters so you'll be able to choose a different library for converting yaml to json.
