### ISSUE TITLE
how about CSV?

### ISSUE THREAD

**Issue by jonschlinkert** [doowb/grunt-convert#7]
I'm working on a project now that _could_ use this with CSV, but I don't know how common that actually is. @hariadi do you think it would be worth it? how often have you worked with CSV?

**Comment by jonschlinkert** [comment]
I think this is worthwhile since csv is sometimes used for i18n translations. I'd like to use https://github.com/wdavidw/node-csv

**Comment by hariadi** [comment]
No problem add suppot to CSV.

I think we need to refactor how we convert format file to another. The idea is, directly require file formats (xml, json, yml or csv) and return json object.

Congratulations on the birth of your new baby, @jonschlinkert!
